### ISSUE TITLE
Assignment to constant variable in error path

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-couch2pg#140]
```
[2023-06-27T20:58:21.779Z ERROR]:  An unrecoverable error occurred
[2023-06-27T20:58:21.779Z ERROR]:  TypeError: Assignment to constant variable.
    at Object.run (/var/adapter/shared/cht-couch2pg-v3.6.2/node_modules/cht-couch2pg/libs/medic/runner.js:77:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2023-06-27T20:58:21.780Z ERROR]:  exiting
```

**Comment by binokaryg** [comment]
Looks like similar looking error was [fixed](https://github.com/medic/config-nssd/issues/167) for config-nssd in the past by @yrimal.
Would you be able to look at it?

**Comment by derickl** [comment]
Is this easily reproducible? Do you have access to a longer stack trace?
