### ISSUE TITLE
Handle case when telemetry dates are null

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-couch2pg#144]
There's an issue in CHT 4.5 where telemetry documents might miss the `year`,`month`,and `day` and because of this cht-couch2pg fails for all projects running CHT 4.5 or later until medic/cht-core#8837 is fixed. 

```
[2024-01-31T19:32:18.890Z ERROR]:  error: invalid input syntax for type date: "1"
    at Parser.parseErrorMessage (/var/adapter/shared/cht-couch2pg-v3.6.2/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/var/adapter/shared/cht-couch2pg-v3.6.2/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/var/adapter/shared/cht-couch2pg-v3.6.2/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/var/adapter/shared/cht-couch2pg-v3.6.2/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 235,
  severity: 'ERROR',
  code: '22007',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL statement "REFRESH MATERIALIZED VIEW CONCURRENTLY useview_telemetry"\n' +
    'PL/pgSQL function refresh_matviews() line 15 at EXECUTE',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'datetime.c',
  line: '3909',
  routine: 'DateTimeParseError',
  query: 'SELECT refresh_matviews()',

```

**Comment by 1yuv** [comment]
Hi @kennsippell , I think it's better to have these `null` dates converted to default time `1970-1-1`. This will allow all projects to still have telemetry objects and continue database sync without failure.

**Comment by 1yuv** [comment]
Closing this issue without merging the work on main branch since the issue was with Nepali projects only and we planned not to release this one with drop cascade, since affected projects were handled individually. The changes have been applied manually to affected projects from #145 .
